<?php
/**
 * proof of concept to test flickr apis
 * 
 * */
class Flickr { 
	/**
	 * key generated by flickr
	 * */
	private $api_key = 'bfee576b92e98e730de5b26a82a11c45'; 
 	/**
 	 * search function from flickr apis
 	 * 
 	 **/
	public function search($params = array()) {
		
		$search = 'http://flickr.com/services/rest/?';		
		if (empty($params)) 
		{
			$params = array();
		}
		$params['api_key'] = $this->api_key;
		$params['method'] = 'flickr.photos.search';
		$params['format'] = 'json';

		if(empty($params)) $params = array();
		foreach($params as $var => $val) {
			$var = urlencode($var);
			$val = urlencode($val);
			$search .= "&$var=$val";
		}
		return $result = file_get_contents($search);
	}
}
$flickr_object =  new Flickr();
echo $flickr_object->search(array('text'=>'car','page'=>$_GET['page'],'per_page'=>'5'));